@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name authenticate
POST {{baseUrl}}/authenticate
Content-Type: application/json

{
  "email": "admin@admin.com"
}

###

# @name sign_out
POST {{baseUrl}}/sign-out


###

# @name auth_from_link
GET http://localhost:3333/auth-links/authenticate?code=lj1oy9opb12otmq9uu8mpu34&redirect=http%3A%2F%2Flocalhost%3A5173
Content-Type: application/json
# Authorization: Bearer {{authToken}}

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json

###

# @name get_managed_restaurant
GET {{baseUrl}}/managed-restaurant
Content-Type: application/json

###

# @name get_order_details
GET {{baseUrl}}/orders/oc7v6si16qhpma2fo34dqze9
Content-Type: application/json

###

# @name approve_order
PATCH {{baseUrl}}/orders/b8oov2hs0gx8qasnwjlosfal/approve

###

# @name dispatch_order
PATCH {{baseUrl}}/orders/b8oov2hs0gx8qasnwjlosfal/dispatch

###

# @name deliver_order
PATCH {{baseUrl}}/orders/b8oov2hs0gx8qasnwjlosfal/deliver

###

# @name cancel_order
PATCH {{baseUrl}}/orders/oc7v6si16qhpma2fo34dqze9/cancel