@baseUrl = http://localhost:3333


# @name authenticate
POST {{baseUrl}}/authenticate
Content-Type: application/json

{
  "email": "admin@admin.com"
}

###

# @name sign_out
POST {{baseUrl}}/sign-out


###

# @name auth_from_link
GET http://localhost:3333/auth-links/authenticate?code=zoii0j520qmdz2o37wow29du&redirect=http%3A%2F%2Flocalhost%3A5173
Content-Type: application/json

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json

###

# @name get_managed_restaurant
GET {{baseUrl}}/managed-restaurant
Content-Type: application/json

###

# @name get_order_details
GET {{baseUrl}}/orders/kwkcaqlzt4ozukx0lleq9hjw
Content-Type: application/json

###

# @name approve_order
PATCH {{baseUrl}}/orders/b8oov2hs0gx8qasnwjlosfal/approve

###

# @name dispatch_order
PATCH {{baseUrl}}/orders/b8oov2hs0gx8qasnwjlosfal/dispatch

###

# @name deliver_order
PATCH {{baseUrl}}/orders/b8oov2hs0gx8qasnwjlosfal/deliver

###

# @name cancel_order
PATCH {{baseUrl}}/orders/oc7v6si16qhpma2fo34dqze9/cancel

###

# @name get_orders
GET {{baseUrl}}/orders?pageIndex=0

###

# @name get_month_revenue
GET {{baseUrl}}/metrics/month-revenue

###

# @name get_day_orders
GET {{baseUrl}}/metrics/day-orders-amount

###

# @name get_month_orders
GET {{baseUrl}}/metrics/month-orders-amount

###

# @name get_canceled_month_orders
GET {{baseUrl}}/metrics/canceled-month-orders-amount